banking/config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, only: :sessions

  root to: 'customers#show'
end

banking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

banking/app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :email, :username, :account
  validates_presence_of :email, :username, :account, :message, :password
end

banking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_in, keys: %i[account password]
  end
end

banking/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show; end
end

banking/app/helpers/application_helper.rb
module ApplicationHelper
end

banking/app/views/customers/show.html.erb
<div class="d-flex justify-content-center">
  <div>
    <h1>Olá <%= "#{current_customer.username} - #{current_customer.account}" %>!</h1>
    <p>Mensagem do gerente: <%= current_customer.message %></p>

    <%= link_to 'Sair', destroy_customer_session_path, data: { 'turbo-method' => :delete }, class: "btn btn-danger" %>
  </div>
</div>

banking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container pt-5">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

banking/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

banking/app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-cashway">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'cashway-logo.jpeg' %>
      Banking
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if customer_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Sair', destroy_customer_session_path, data: { 'turbo-method' => :delete }, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>