gerencial/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: :sessions
  devise_for :customers, only: :registrations, controllers: { registrations: 'customers/registrations' }

  root 'home#index'
  resources :customers, only: :show
end

gerencial/app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
  validates_presence_of :email, :password
end

gerencial/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gerencial/app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :email, :username, :account
  validates_presence_of :email, :username, :account, :message, :password
end

gerencial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
end

gerencial/app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customer_path(@customer)
    else
      redirect_to new_customer_registration_path, alert: 'Ops, algo deu errado!'
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username account message])
  end

  def customer_params
    params.require(:customer).permit(:username, :account, :email, :message, :password, :password_confirmation)
  end
end

gerencial/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end
end

gerencial/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_admin!, only: :index

  def index; end
end

gerencial/app/helpers/application_helper.rb
module ApplicationHelper
end

gerencial/app/helpers/customers_helper.rb
module CustomersHelper
end

gerencial/app/helpers/home_helper.rb
module HomeHelper
end

gerencial/app/views/customers/show.html.erb
<div class="d-flex justify-content-center">
  <div>
    <h1>Cliente <%= @customer.username %> cadastrado!</h1>
    <p>Conta: <%= @customer.account %></p>
    <p>Email: <%= @customer.email %></p>
    <p>Mensagem: <%= @customer.message %></p>

    <%= link_to "Cadastrar cliente", new_customer_registration_path, class: "btn btn-primary" %>
    <%= link_to 'Sair', destroy_admin_session_path, data: { 'turbo-method' => :delete }, class: "btn btn-danger" %>
  </div>
</div>

gerencial/app/views/home/index.html.erb
<div class="d-flex justify-content-center">
  <div>
    <% if admin_signed_in? %>
      <h1>Olá!</h1>
      <p>Você deseja cadastrar um novo cliente?</p>
      <%= link_to "Cadastrar cliente", new_customer_registration_path, class: 'btn btn-primary' %>
      <%= link_to "Sair", destroy_admin_session_path, data: { 'turbo-method' => :delete }, class: 'btn btn-danger' %>
    <% else %>
      <h1>Bem vindo!</h1>
      <p>Deseja acessar nossa plataforma administrativa?</p>
      <%= link_to "Login", new_admin_session_path, class: 'btn btn-primary'  %>
    <%end%>
  </div>
</div>

gerencial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerencial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container pt-5">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

gerencial/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

gerencial/app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-cashway">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'cashway-logo.jpeg' %>
      Gerencial
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "Cadastrar Cliente", new_customer_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>